use classicmodels;

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE STATE IS NULL;
SELECT CONTACTFIRSTNAME,CONTACTLASTNAME,CONCAT_WS(" ",CONTACTFIRSTNAME,CONTACTLASTNAME) AS 'FULL NAME' FROM CUSTOMERS;
SELECT contactlastname,customernumber,CONCAT(CONTACTLASTNAME,CUSTOMERNUMBER,"@classicmodels.com") AS email FROM CUSTOMERS;
SELECT LOWER(COUNTRY) AS COUNTRY,COUNT(*) AS TOTAL_COUNT FROM CUSTOMERS GROUP BY COUNTRY ORDER BY TOTAL_COUNT DESC;
SELECT LOWER(COUNTRY) AS COUNTRY,COUNT(*) AS TOTAL_COUNT FROM CUSTOMERS GROUP BY COUNTRY ORDER BY TOTAL_COUNT DESC LIMIT 3;