use movies;
create table if not exists telugu_movies(
id int,
movie_name varchar(30),
director varchar(30),
duration int);

DESCRIBE TELUGU_MOVIES;

CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENTS(STDID INT PRIMARY KEY AUTO_INCREMENT  ,
NAME varchar(30) NOT NULL,
GENDER varchar(30) NOT NULL,
CLASS INT);

DESCRIBE STUDENTS;

USE SCHOOL;
ALTER TABLE STUDENTS ADD COLUMN AGE TINYINT CHECK(AGE>5);
ALTER TABLE STUDENTS ADD COLUMN DATE_OF_BIRTH DATE;
ALTER TABLE STUDENTS ADD COLUMN LOCATION VARCHAR(50),ADD COLUMN ADDRESS VARCHAR(30);
ALTER TABLE STUDENTS DROP LOCATION,DROP ADDRESS;

ALTER TABLE STUDENTS MODIFY COLUMN GENDER ENUM('MALE','FEMALE');
ALTER TABLE STUDENTS MODIFY COLUMN CLASS TINYINT UNSIGNED NOT NULL;

CREATE TABLE MARKS(
STDID INT,
S1 INT,
S2 INT,
S3 INT,
PERCENTAGE DECIMAL(4,2),
FOREIGN KEY (STDID) REFERENCES STUDENTS(STDID));