use classicmodels;
select * from customers;
select * from orders;
select * from employees;

-- GET THE CUSTOMER DETAILS WHO PLACED AN ORDER
SELECT C.CUSTOMERNUMBER,CUSTOMERNAME,ORDERNUMBER FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERNUMBER=O.CUSTOMERNUMBER;

-- WHICH CUSTOMERS HAVE DISTINCT SHIPPED ORDERS (CUSTOMER NUMBER, NAME, ORDER NUMBER)?
SELECT DISTINCT C.CUSTOMERNUMBER,CUSTOMERNAME,ORDERNUMBER FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERNUMBER=O.CUSTOMERNUMBER
WHERE O.STATUS="SHIPPED";

-- WHICH CUSTOMERS HAVE DISTINCT CANCELLED ORDERS (CUSTOMER NUMBER, NAME, ORDER NUMBER)?
SELECT DISTINCT C.CUSTOMERNUMBER,CUSTOMERNAME,ORDERNUMBER FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERNUMBER=O.CUSTOMERNUMBER
WHERE O.STATUS="CANCELLED";

-- EQUIE JOIN
-- WHICH CUSTOMERS HAVE CANCELLED ORDERS, USING EQUI JOIN SYNTAX?
SELECT C.CUSTOMERNUMBER,CUSTOMERNAME,ORDERNUMBER FROM CUSTOMERS C,ORDERS O
WHERE C.CUSTOMERNUMBER = O.CUSTOMERNUMBER AND O.STATUS = "CANCELLED";

-- GET EACH CUSTOMERS TOTAL ORDERS COUNT
SELECT C.CUSTOMERNUMBER,CUSTOMERNAME,COUNT(*) TOTAL_ORDERS FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERNUMBER=O.CUSTOMERNUMBER
GROUP BY C.CUSTOMERNUMBER
ORDER BY TOTAL_ORDERS DESC;

-- GET EACH CUSTOMER TOTAL SHIPPED ORDERS COUNT
SELECT C.CUSTOMERNUMBER,CUSTOMERNAME,COUNT(*) TOTAL_ORDERS FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERNUMBER=O.CUSTOMERNUMBER
WHERE O.STATUS="SHIPPED"
GROUP BY C.CUSTOMERNUMBER
ORDER BY TOTAL_ORDERS DESC;

-- WHICH CUSTOMERS HAVE MORE THAN 3 SHIPPED ORDERS, SORTED BY TOTAL ORDERS (HIGHEST FIRST)?
SELECT C.CUSTOMERNUMBER,CUSTOMERNAME,COUNT(*) TOTAL_ORDERS FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERNUMBER=O.CUSTOMERNUMBER
WHERE O.STATUS="SHIPPED"
GROUP BY C.CUSTOMERNUMBER
HAVING COUNT(*)>3
ORDER BY TOTAL_ORDERS DESC;

-- NATURAL JOIN
-- GET THE ORDER PLACED CUSTOMER DETAILS
SELECT DISTINCT C.CUSTOMERNUMBER , CUSTOMERNAME FROM CUSTOMERS C
NATURAL JOIN ORDERS O;

-- WHICH CUSTOMERS HAVE EMPLOYEE NUMBER DETAILS VIA NATURAL JOIN?
SELECT DISTINCT C.CUSTOMERNUMBER , CUSTOMERNAME,EMPLOYEENUMBER FROM CUSTOMERS C
NATURAL JOIN EMPLOYEES;

-- CROSS JOIN
-- WHAT IS THE CROSS JOIN RESULT OF EVERY CUSTOMER PAIRED WITH EVERY EMPLOYEE?
SELECT C.CUSTOMERNUMBER , CUSTOMERNAME,EMPLOYEENUMBER FROM CUSTOMERS C
CROSS JOIN EMPLOYEES;