CREATE DATABASE IT_COMPANY;

USE IT_COMPANY;

CREATE TABLE EMPLOYEES(ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30),
DEPT VARCHAR(20),
SALARY INT UNSIGNED);

INSERT INTO EMPLOYEES(NAME,DEPT,SALARY)
VALUES("RAVI","IT",50000),("KAVI","HR",40000),("KIRAN","SALES",50000),("SRINU","IT",50000),("SRAVAN","HR",52000),("SEKHAR","SALES",70000),("RAJ","IT",90000),
("CHANDRA","HR",20000),("KISHORE","SALES",30000),("PREETHAM","IT",52000),("HARDHIK","HR",53000);

-- SUB QUERIES
-- SINGLE ROW SUBQUERY
SELECT * FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES WHERE SALARY=(SELECT MIN(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES WHERE DEPT=(SELECT DEPT FROM EMPLOYEES WHERE NAME="RAVI") AND NAME != "RAVI";

SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES)
OR SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

-- MULTIROW SUBQUERY
SELECT * FROM EMPLOYEES WHERE DEPT IN (SELECT DEPT FROM EMPLOYEES WHERE NAME IN ("KAVI","KISHORE"));

SELECT * FROM EMPLOYEES WHERE SALARY > ANY(SELECT SALARY FROM EMPLOYEES WHERE DEPT = "SALES");

SELECT DEPT,AVG(SALARY) FROM EMPLOYEES
GROUP BY DEPT HAVING AVG(SALARY) > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT * FROM
(SELECT DEPT ,COUNT(*) FROM EMPLOYEES GROUP BY DEPT HAVING COUNT(*)>3) AS TABLEE;

SELECT * FROM
(SELECT DEPT ,COUNT(*) AS TOTALCOUNT FROM EMPLOYEES GROUP BY DEPT) AS TABLEE WHERE TOTALCOUNT>3;

-- CORELATED SUB QUERY
-- GET THE EMPLOYEE DETAILS WHOSE SALARY IS GREATER THAN THEIR DEPARTMENT'S AVERAGE SALARY
SELECT * FROM EMPLOYEES E1
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES E2 WHERE E1.DEPT=E2.DEPT);


-- GET THE EACH DEPT MAX SALARY EMPLOYEE DETAILS
SELECT * FROM EMPLOYEES E1
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES E2 WHERE E1.DEPT=E2.DEPT);

SELECT * FROM EMPLOYEES E1
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES E2 WHERE E1.DEPT=E2.DEPT);